version: '3.8'

networks:
  car-fix-guru-network:
    driver: bridge

services:

  postgres:
    #env_file: ./docker-env.env
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORF=Varchar2
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - car-fix-guru-network

volumes:
  pgdata:
    external: true